name: RAX3000M-EMMC

on:
  repository_dispatch:
  workflow_dispatch:
    inputs:             
      OP_IP:
        description: '静态IP地址'     
        required: false
        default: '192.168.92.200' 
        type: string
      OP_author:
        description: '定制作者'     
        required: false
        default: 'L' 
        type: string    
      CUSTOM_PLUGINS:
        description: '自定义插件名称，用空格分隔'
        required: false
        default: 'luci-app-dockerman cryptsetup nfs-kernel-server'
        type: string

#设置仓库的读写权限
permissions:
  contents: write

jobs:
  build_firmware:
    runs-on: ubuntu-22.04

    steps: 
    - name: 检查分支
      uses: actions/checkout@v6

    - name: 准备可用空间
      uses: AdityaGarg8/remove-unwanted-software@v5
      with:
        remove-dotnet: true
        remove-android: true
        remove-haskell: true
        remove-codeql: true
        remove-docker-images: true
        remove-large-packages: true
        remove-cached-tools: true
        remove-swapfile: true

    - name: 检出代码
      uses: actions/checkout@v6

    - name: 编译环境
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        sudo apt-get update
        sudo apt-get install -y tar build-essential flex bison cmake g++ gawk gcc-multilib g++-multilib gettext git libfuse-dev libncurses5-dev libssl-dev python3 python3-pip python3-ply python3-distutils python3-pyelftools rsync unzip zlib1g-dev file wget subversion patch upx-ucl autoconf automake curl asciidoc binutils bzip2 lib32gcc-s1 libc6-dev-i386 uglifyjs msmtp texinfo libreadline-dev libglib2.0-dev xmlto libelf-dev libtool autopoint antlr3 gperf ccache swig coreutils haveged scons libpython3-dev rename qemu-utils
        sudo apt-get clean
        git config --global user.name 'GitHub Actions' && git config --global user.email 'noreply@github.com'
        sudo timedatectl set-timezone 'Asia/Shanghai'
        sudo mkdir -p /workdir
        sudo chown $USER:$GROUPS /workdir
        df -Th

    - name: 设置环境变量
      run: |
        TAG="$(date +'%Y%m%d')"
        echo "tag=$TAG" >> $GITHUB_ENV
        echo "OP_IP=${{ github.event.inputs.OP_IP }}" >> $GITHUB_ENV
        echo "OP_author=${{ github.event.inputs.OP_author }}" >> $GITHUB_ENV
        echo "CUSTOM_PLUGINS=${{ github.event.inputs.CUSTOM_PLUGINS }}" >> $GITHUB_ENV
        echo "REPO_BRANCH=RAX3000M" >> $GITHUB_ENV

    - name: 克隆源代码
      working-directory: /workdir
      run: |
        df -hT $PWD
        git clone https://github.com/padavanonly/immortalwrt-mt798x-6.6 openwrt
        ln -sf /workdir/openwrt $GITHUB_WORKSPACE/openwrt
        
    - name: 更新源
      run: |
        set -x
        cd openwrt
        ./scripts/feeds update -a
        ./scripts/feeds install -a 

    - name: 自动缓存管理
      uses: HiGarfield/cachewrtbuild@main
      with:
        toolchain: true
        ccache: true
        mixkey: RAX3000M-EMMC
        prefix: openwrt

    - name: 加载自定义配置
      run: |
        cd openwrt
        cp defconfig/mt7981-ax3000.config .config
        # 选择RAX3000M-EMMC
        echo "CONFIG_TARGET_mediatek_filogic_DEVICE_cmcc_rax3000m-emmc-mtk=y" >> .config 
        # 加载自定义插件配置
        sed -i '/CONFIG_PACKAGE_tcpdump=y/d' .config  # 删除tcpdump
        
        # 默认集成插件列表
        default_plugins=(luci-theme-argon luci-app-hd-idle openssh-sftp-server htop fdisk sshpass tcpdump-mini lsblk parted rsync kmod-tun iperf3 kmod-fs-ext4 kmod-usb-storage kmod-usb-storage-uas)
        
        # 添加默认插件
        for plugin in "${default_plugins[@]}"; do
          echo "CONFIG_PACKAGE_${plugin}=y" >> .config
        done
        echo "已添加默认插件: ${default_plugins[*]}"
        
        # 添加用户自定义插件
        IFS=' ' read -r -a plugins <<< "${{ github.event.inputs.CUSTOM_PLUGINS }}"
        for plugin in "${plugins[@]}"; do
          echo "CONFIG_PACKAGE_${plugin}=y" >> .config
        done
        echo "已添加自定义插件: ${plugins[@]}"
        #修改nfs内核编译报错
        sed -i '/-Wno-error=missing-include-dirs/i\		-Wno-error=format-nonliteral \\' feeds/packages/net/nfs-kernel-server/Makefile

        #设置ip
        sed -i "s/192.168.6.1/${{ github.event.inputs.OP_IP }}/" package/base-files/files/bin/config_generate

        # 修改 WiFi 配置
        sed -i "s/ssid=\"ImmortalWrt-2.4G\"/ssid=\"2.4\"/g" package/mtk/applications/mtwifi-cfg/files/mtwifi.sh
        sed -i "s/ssid=\"ImmortalWrt-5G\"/ssid=\"5\"/g" package/mtk/applications/mtwifi-cfg/files/mtwifi.sh
        sed -i 's/set wireless.default_${dev}.encryption=none/set wireless.default_${dev}.encryption=psk2\n\t\tset wireless.default_${dev}.key="12345678asd"/g' openwrt/package/mtk/applications/mtwifi-cfg/files/mtwifi.sh

        # 修改banner
        sed -i "s/ImmortalWrt-798x-24.10 from PadavanOnly/$(date +'%Y-%m-%d') by L/g" files/etc/banner

        # 修改内核vermagic
        sed -i 's|.*.vermagic.*|\techo "95e6bd5cddf3ff6cfc1d156be2d8a213" > $(LINUX_DIR)/.vermagic|' include/kernel-defaults.mk

        # 添加wifi日志控制
        cp ../RAX3000M/rt_linux.patch .
        patch -p1 < rt_linux.patch


    
    - name: 下载编译依赖
      id: package
      run: |
        cd openwrt
        make defconfig
        make download -j8
        find dl -size -1024c -exec ls -l {} \;
        find dl -size -1024c -exec rm -f {} \;
  

    - name: 编译源码
      id: compile
      run: |
        cd openwrt
        echo -e "$(nproc) thread compile"
        make -j$(nproc) || make -j1 V=s

    - name: 查看磁盘使用情况
      if: (!cancelled())
      run: df -hT

    - name: 整理文件
      id: organize
      run: |
        cp openwrt/.config openwrt/bin/targets/*/*/
        cd openwrt/bin/targets/*/*
        rm -rf packages
        rm -rf *.buildinfo
        rm -rf profiles.json
        rm -rf *.manifest
        rm -rf *bl2.bin
        rm -rf *kernel.bin
        rm -rf *.sha
        rm -rf sha256sums
        echo "FIRMWARE=$PWD" >> $GITHUB_ENV

    - name: 上传固件到Releases
      uses: softprops/action-gh-release@v2
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ env.tag }}
        files: ${{ env.FIRMWARE }}/*
        body: |
          ====================固件信息=======================
          静态IP：${{ github.event.inputs.OP_IP }}
          插件：${{ github.event.inputs.CUSTOM_PLUGINS }}
          定制作者：${{ github.event.inputs.OP_author }}

    #- name: 清理Releases
    #  uses: dev-drprasad/delete-older-releases@v0.3.4
    #  with:
    #    keep_latest: 1
    #    delete_tags: true
    #  env:
    #    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    #    - name: 切换分支
    #  run: |
    #    cd openwrt
    #    git checkout RAX3000M
